# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: "en-US"
title: Fendi, Take Me to Eat! # Title on the both website header (masthead) and the website tab"
title_separator: "-"
masthead_title: "Take Me To Eat!" # This will override the website header (it's called masthead)
name: "Fendi Tjoa"
url: "https://fendihalim.github.io/" # not sure if needed to be writte. initially a blank
baseurl: "/FendiFinds" # not sure if needed to be written. initially a blank
words_per_minute: 200 # the speed set to read the article. this is connected to read_time under default below
email: fenditakemetoeat@gmail.com
description: "Easy recipes, honest coffee reviews, and budget-friendly cooking tips for home cooks and college students."
twitter_username: fendihalim
github_username: fendihalim
minimal_mistakes_skin: "dirt"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Fendi Tjoa "
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "A passionate home cook and food lover sharing easy recipes, honest reviews, and kitchen tips for everyday eaters"
  location: "Toronto, Ontario, CANADA :canada:"
  email: fenditakemetoeat@gmail.com
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://fendihalim.github.io/FendiFinds/"
    # - label: "Reddit"
    #   icon: "fab fa-fw fa-square-reddit" 
    #   url: "https://www.reddit.com/user/FendiFinds/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/fendihalim/FendiFinds"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  since: "2025"
  # links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    # - label: "Reddit"
    #   icon: "fab fa-fw fa-square-reddit" 
    #   url: "https://www.reddit.com/user/FendiFinds/"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/fendihalim/FendiFinds"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

comments:
  provider: "disqus"
  disqus:
    shortname: "FendiFinds"

atom_feed:
  hide: true
lunr:
  search_within_pages: true
google_site_verification: "RTGRSh1HCRm0YlRRyeJiagDUW5wtJ8df6KKZpO4g0G8"
analytics:
  provider: "google-gtag"
  google: 
    tracking_id: "G-JCHGEECWWT"
    anonymize_ip: false

collections:
  recipes:
    output: true
    permalink: /recipes/:title/
  journals:
    output: true
    permalink: /journals/:year/:month/:day/:title/
  kitchens:
    output: true
    permalink: /kitchens/:title/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


