# _config.yml

title: "Fendi, Take Me to Eat!"
description: "Easy recipes, coffee reviews, and budget bites."
url: "https://fendihalim.github.io"
baseurl: "/takemetoeat"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

# Recommended extras for MM
markdown: kramdown
kramdown:
  input: GFM

nav:
  - title: Home
    url: /
  - title: About Me
    url: /about/

# Optional: your social links
author:
  name: Fendi Tjoa
  location: Toronto, Ontario, Canada
  email: fenditakemetoeat@gmail.com
description: "Great site about food related reviews and less-mess food recipes"
