title: "Fendi, Take Me to Eat!"
description: "Easy recipes, coffee reviews, and budget bites."
url: "https://fendihalim.github.io"
baseurl: "/takemetoeat"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM

nav:
  - title: Home
    url: /takemetoeat/
  - title: About Me
    url: /takemetoeat/about/

author:
  name: Fendi Tjoa
  location: Toronto, Ontario, Canada
  email: fenditakemetoeat@gmail.com
